# basic setup
FROM ubuntu:18.04
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
RUN apt-get -y update
RUN apt-get install -y python3 python3-pip

# application specific configuration
EXPOSE 5000
RUN mkdir /app
WORKDIR /app
COPY requirements.txt /app/
RUN pip3 install --requirement requirements.txt
COPY src /app/
CMD python3 -m asobann.deploy ; python3 -m asobann.wsgi
