version: '3'
services:
    test:
        build:
          context: ../..
          dockerfile: Dockerfile.localdev.test
        volumes:
            - ../../:/app

    app_1:
        build:
          context: ../..
          dockerfile: Dockerfile.localdev
        ports:
            - "8000:5000"
        volumes:
            - ../../:/app
        environment:
            MONGODB_URI: mongodb://admin:password@mongo:27017
            REDIS_URI: redis://redis:6379

    app_2:
        build:
            context: ../..
            dockerfile: Dockerfile.localdev
        ports:
            - "8001:5000"
        volumes:
            - ../../:/app
        environment:
            MONGODB_URI: mongodb://admin:password@mongo:27017
            REDIS_URI: redis://redis:6379

    app_3:
        build:
            context: ../..
            dockerfile: Dockerfile.localdev
        ports:
            - "8002:5000"
        volumes:
            - ../../:/app
        environment:
            MONGODB_URI: mongodb://admin:password@mongo:27017
            REDIS_URI: redis://redis:6379

    redis:
        image: redis
        ports:
            - "6379"

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - "27017"
        volumes:
            - ./mongodata/db:/data/db
            - ./mongodata/configdb:/data/configdb
