version: '3'
services:
    app_1:
        build: app/
        ports:
            - "5000"
        volumes:
            - ../../:/app
        environment:
            MONGODB_URI: mongodb://admin:password@mongo:27017
            REDIS_URI: redis://redis:6379

    app_2:
        build: app/
        ports:
            - "5000"
        volumes:
            - ../../:/app
        environment:
            MONGODB_URI: mongodb://admin:password@mongo:27017
            REDIS_URI: redis://redis:6379

    app_3:
        build: app/
        ports:
            - "5000"
        volumes:
            - ../../:/app
        environment:
            MONGODB_URI: mongodb://admin:password@mongo:27017
            REDIS_URI: redis://redis:6379

    redis:
        image: redis
        ports:
            - "6379"

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - "27017"
        volumes:
            - ./mongodata/db:/data/db
            - ./mongodata/configdb:/data/configdb

    web:
        image: nginx
        ports:
            - "8888:80"
        volumes:
            - './web/nginx.conf:/etc/nginx/nginx.conf'