import os

import asobann.config_common as common

MONGO_URI = os.environ["MONGODB_URI"]
PORT = 5000
REDIS_URI = common.REDIS_URI
BASE_URL = 'http://localhost:5000'
GOOGLE_ANALYTICS_ID = None

if 'ASOBANN_DEBUG_HANDLER_WAIT' in os.environ:
    DEBUG_HANDLER_WAIT = common.from_env('ASOBANN_DEBUG_HANDLER_WAIT', default=None)

UPLOADED_IMAGE_STORE = common.UPLOADED_IMAGE_STORE
AWS_KEY = common.AWS_KEY
AWS_SECRET = common.AWS_SECRET
AWS_REGION = common.AWS_REGION
AWS_S3_IMAGE_BUCKET_NAME = common.AWS_S3_IMAGE_BUCKET_NAME

AWS_COGNITO_USER_POOL_ID = common.AWS_COGNITO_USER_POOL_ID
AWS_COGNITO_CLIENT_ID = common.AWS_COGNITO_CLIENT_ID

if 'ASOBANN_DEBUG_OPTS' in os.environ:
    opts = os.environ['ASOBANN_DEBUG_OPTS'].split(',')
    DEBUG_PERFORMANCE_RECORDING = 'PERFORMANCE_RECORDING' in opts
    DEBUG_ORDER_OF_UPDATES = 'ORDER_OF_UPDATES' in opts
    DEBUG_LOG = 'LOG' in opts

if "ASOBANN_ACCESS_LOG" in os.environ:
    ACCESS_LOG = True
else:
    ACCESS_LOG = False
